apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qaq-dev

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: uniauth-api-conf
    files:
      - application.yaml